name: Python Linting and Testing

on:
  push:
    branches:
      - main
      - dev  # Runs on both main and dev branches
  pull_request:
    branches:
      - main
      - dev  # Also runs on pull requests to both branches

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black pytest
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Format with black
        run: black --check .

      # - name: Run tests
      #   run: pytest
